#!/bin/bash

cd ../src/canisters/omnia_backend

# --branch option can be specified
BRANCH="main"
if [ "$1" = "--branch" ]; then
  if [ -z "$2" ]; then
    echo "Error: --branch option requires a branch name"
    exit 1
  else
    BRANCH="$2"
  fi
fi

echo "Generating backend types from branch: $BRANCH"

# download the latest version of omnia-backend.did
curl -s https://raw.githubusercontent.com/omnia-network/omnia-backend/$BRANCH/src/omnia_backend/omnia_backend.did > omnia_backend.did

# generate the candid types
../../../bin/didc bind omnia_backend.did -t ts > ./omnia_backend.did.d.ts
../../../bin/didc bind omnia_backend.did -t js > ./omnia_backend.did.js

# prepend a "this is an auto-generated file" comment
sed -i '1s/^/\/\/ This file is auto-generated by the generate-omnia-backend-types.sh script. Do not edit it manually.\n\n/' ./omnia_backend.did.d.ts
sed -i '1s/^/\/\/ This file is auto-generated by the generate-omnia-backend-types.sh script. Do not edit it manually.\n\n/' ./omnia_backend.did.js

echo "Generated omnia-backend types."

# fetch the last commit hash for the branch
LAST_COMMIT=$(git ls-remote https://github.com/omnia-network/omnia-backend.git refs/heads/$BRANCH | cut -f 1)

# log the git tree
echo -e "\nPlease commit the types update with this message:\n\"\"\"\nupdate omnia-backend types ($BRANCH branch)\n\nfrom: https://github.com/omnia-network/omnia-backend/tree/$LAST_COMMIT\n\"\"\""
