// This file is auto-generated by the generate-omnia-backend-types.sh script. Do not edit it manually.

export const idlFactory = ({ IDL }) => {
  const EnvironmentCreationInput = IDL.Record({ 'env_name' : IDL.Text });
  const EnvironmentCreationResult = IDL.Record({
    'env_uid' : IDL.Nat32,
    'env_name' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'user_principal_id' : IDL.Text,
    'environment_uid' : IDL.Opt(IDL.Nat32),
  });
  const DeviceRegistrationInput = IDL.Record({
    'device_name' : IDL.Text,
    'env_uid' : IDL.Nat32,
    'gateway_uid' : IDL.Nat32,
  });
  const DeviceRegistrationResult = IDL.Record({
    'device_name' : IDL.Text,
    'device_uid' : IDL.Nat32,
  });
  const GatewayRegistrationInput = IDL.Record({
    'gateway_name' : IDL.Text,
    'env_uid' : IDL.Nat32,
  });
  const GatewayRegistrationResult = IDL.Record({
    'gateway_name' : IDL.Text,
    'gateway_uid' : IDL.Nat32,
  });
  const EnvironmentInfo = IDL.Record({
    'env_manager_principal_id' : IDL.Text,
    'env_uid' : IDL.Nat32,
    'env_name' : IDL.Text,
  });
  return IDL.Service({
    'createEnvironment' : IDL.Func(
        [EnvironmentCreationInput],
        [EnvironmentCreationResult],
        [],
      ),
    'getProfile' : IDL.Func([], [UserProfile], []),
    'registerDevice' : IDL.Func(
        [DeviceRegistrationInput],
        [DeviceRegistrationResult],
        [],
      ),
    'registerGateway' : IDL.Func(
        [GatewayRegistrationInput],
        [GatewayRegistrationResult],
        [],
      ),
    'resetEnvironment' : IDL.Func([], [EnvironmentInfo], []),
    'setEnvironment' : IDL.Func([IDL.Nat32], [EnvironmentInfo], []),
  });
};
export const init = ({ IDL }) => { return []; };
